### ISSUE TITLE
Integer only values don't work in filters

### ISSUE THREAD

**Issue by salmonweb** [skokenes/senseUtils#2]
When creating a filter for years, the filter doesn't work. When I append a string to the integer it does work.

**Comment by phlekk** [comment]
Hi,

i have the same problem.

comment line 180-182

 `app.field(field).selectValues([{
                        qText : e.qText
                    }], true, false);`

and use this -> `app.field(field).select([e.qElemNumber],true,true);`

That works for me.

**Comment by skokenes** [comment]
Thanks, I will add this change
